name:                hs-cmdstan
version:             0.1.0.0
github:              "githubuser/hs-cmdstan"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hs-cmdstan#readme>

dependencies:
- base >= 4.7 && < 5
- directory
- process
- filepath
- megaparsec
- containers

ghc-options:
- -Wall

default-extensions:
- RecordWildCards
- LambdaCase
- DeriveGeneric
- QuasiQuotes
- TupleSections

library:
  source-dirs: src

executables:
  example:
    main: Main.hs
    source-dirs: examples
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-cmdstan
    - async

tests:
  hs-cmdstan-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-cmdstan
    - hspec
    - megaparsec
    - here
